apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: mongo-operator
  name: mongo-operator
  namespace: mongo-operator-cluster
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: mongo-operator
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongo-operator
    spec:
      containers:
      - image: ultimaker/k8s-mongo-operator:local
        imagePullPolicy: Never
        name: mongo-operator
        env:
        - name: LOGGING_LEVEL
          value: DEBUG
      serviceAccount: mongo-operator-service-account
