apiVersion: "operators.ultimaker.com/v1"
kind: Mongo
metadata:
  name: mongo-cluster
  namespace: mongo-operator-cluster
  labels:
    app: mongo-cluster
spec:
  mongodb:
    replicas: 5  # Must be between 3 and 50
  backups:
    cron: "0 * * * *"  # every hour at 0 minutes
    gcs:
      bucket: "mongo-backups"
      serviceAccount:
        secretKeyRef:
          key: json
          name: storage-serviceaccount
